site_name: Games4Life Regels
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: nl
  nav:
    - Home: 'index.md'
    - Regels: 'regels.md'
    - About: 'about.md'
  palette:
    - scheme: default
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: purple
copyright: Copyright &copy; 2019 - 2023 Games4Life Community
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/g4life
      name: G4L Community on discord
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@quintyboygames
      name: quintyboygames's youtube kanaal